---
version: '3.6'
services:
  post_db:
    image: mongo:${MONGO_TAG}
    container_name: '${COMPOSE_PROJECT_NAME}_mongo'
    volumes:
      - post_db:/data/db
    networks:
      backend:
        aliases:
          - '${COMPOSE_PROJECT_NAME}-backnet'

  ui:
    build:
      context: ../src/ui
    image: '${REPOSITORY_NAME}/${COMPOSE_PROJECT_NAME}-ui:1.0'
    container_name: '${COMPOSE_PROJECT_NAME}_ui'
    ports:
      - ${UI_PORT}:${UI_PORT}
    restart: always
    depends_on:
      - post_db
    networks:
      backend:
        aliases:
          - '${COMPOSE_PROJECT_NAME}-backnet'
      frontend:
        aliases:
          - '${COMPOSE_PROJECT_NAME}-frontend'

  post:
    build:
      context: ../src/post-py
    image: '${REPOSITORY_NAME}/${COMPOSE_PROJECT_NAME}-post:1.0'
    container_name: '${COMPOSE_PROJECT_NAME}_post'
    networks:
      backend:
        aliases:
          - '${COMPOSE_PROJECT_NAME}-backnet'

  comment:
    build:
      context: ../src/comment
    image: '${REPOSITORY_NAME}/${COMPOSE_PROJECT_NAME}-comment:1.0'
    container_name: '${COMPOSE_PROJECT_NAME}_comment'
    networks:
      backend:
        aliases:
          - '${COMPOSE_PROJECT_NAME}-backnet'

  prometheus:
    build:
      context: ../monitoring/prometheus
    image: '${REPOSITORY_NAME}/${COMPOSE_PROJECT_NAME}-prometheus:latest'
    container_name: '${COMPOSE_PROJECT_NAME}_prometheus'
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      backend:
        aliases:
          - '${COMPOSE_PROJECT_NAME}-backnet'
      frontend:
        aliases:
          - '${COMPOSE_PROJECT_NAME}-frontend'

  node-exporter:
    image: prom/node-exporter:v0.15.2
    container_name: '${COMPOSE_PROJECT_NAME}_node-exporter'
    user: root
    restart: always
    ports:
      - '9100:9100'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      backend:
        aliases:
          - '${COMPOSE_PROJECT_NAME}-backnet'
      frontend:
        aliases:
          - '${COMPOSE_PROJECT_NAME}-frontend'

volumes:
  post_db:
  prometheus_data:

networks:
  backend:
  frontend:
    name: '${COMPOSE_PROJECT_NAME}-network'

